flutter_analyze_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  pub_get_script: flutter pub get
  lint_script: flutter analyze

flutter_test_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test

flutter_drive_ios_task:
  osx_instance:
    image: catalina-xcode-11.6-flutter
  open_simulator_script:
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-13-6 | xargs xcrun simctl boot
  test_script: make test

flutter_drive_android_task:
  container:
    image: cirrusci/flutter:stable
    kvm: true
    cpu: 4
    memory: 24G
  env:
    EMULATOR_API_LEVEL: 29
    ANDROID_ABI: "default;x86_64"
  fix_kvm_script: sudo chown $(whoami):$(whoami) /dev/kvm
  update_emulator_script: sdkmanager --verbose --channel=0 "emulator"
  update_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script: echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script: $ANDROID_HOME/emulator/emulator -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    - ./scripts/android-wait-for-emulator.sh
  pub_cache:
    folder: ~/.pub-cache
  android_cache:
    folder: ~/.android/build-cache/
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: cat buildSrc/dependencies.gradle && cat gradle/wrapper/gradle-wrapper.properties
  cleanup_script:
    - rm -rf ~/.gradle/caches/[0-9].*
    - rm -rf ~/.gradle/caches/transforms-1
    - rm -rf ~/.gradle/caches/journal-1
    - rm -rf ~/.gradle/caches/jars-3/*/buildSrc.jar
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
  test_script: make test
